$ = JQuery = require('jquery')
var React = require('react')
var ReactDOM = require('react-dom')
var EditableTable = require('./components/editableTable')
ReactDOM.render(<EditableTable />, document.getElementById('app'))
